"""initial

Revision ID: b6040d16034f
Revises: 
Create Date: 2026-05-24 16:14:18.881778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6040d16034f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('reliability', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_ratio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ratio_code', sa.String(length=50), nullable=False),
    sa.Column('ratio_name', sa.String(length=255), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('normalization_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('normalization_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ratio_code')
    )
    op.create_table('financial_statement_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_code', sa.String(length=50), nullable=False),
    sa.Column('line_name', sa.String(length=255), nullable=False),
    sa.Column('statement_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('calculation_formula', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['financial_statement_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_code')
    )
    op.create_table('report_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reporting_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('report_type_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_audited', sa.Boolean(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['report_type_id'], ['report_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_year', 'report_type_id', name='uq_company_period_report')
    )
    op.create_table('calculated_ratio_value',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reporting_period_id', sa.Integer(), nullable=False),
    sa.Column('ratio_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ratio_id'], ['financial_ratio.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporting_period_id', 'ratio_id', name='uq_period_ratio')
    )
    op.create_table('financial_statement_value',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reporting_period_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['financial_statement_line.id'], ),
    sa.ForeignKeyConstraint(['reporting_period_id'], ['reporting_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporting_period_id', 'line_id', name='uq_period_line')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_statement_value')
    op.drop_table('calculated_ratio_value')
    op.drop_table('reporting_period')
    op.drop_table('report_type')
    op.drop_table('financial_statement_line')
    op.drop_table('financial_ratio')
    op.drop_table('data_source')
    op.drop_table('company')
    # ### end Alembic commands ###
